### ISSUE TITLE
Action is failing when deploying AKS in custom Vnet

### ISSUE THREAD

**Issue by ma185360** [Azure/aml-compute#29]
Hi Team,

When we are trying to built aks cluster in custom vnet it is failing.We are passing below info in the compute.json. And when we tried to created the cluster manually with same configuration, it worked.

Compute.json:
{
    "name": "testml12",
    "compute_type": "akscluster",
    "agent_count": 3,
    "vm_size": "Standard_D3_v2",
    "location": "northcentralus",
    "service_cidr": "192.168.19.0/24",
    "dns_service_ip": "192.168.19.10",
    "docker_bridge_cidr": "172.19.0.1/16",
    "cluster_purpose": "DevTest",
    "vnet_resource_group_name": "vnet-rg",
    "vnet_name": "ml-vnet-workerpool",
    "subnet_name": "ml-subnet-1",
    "load_balancer_type": "PublicIp"
}

Error:

***
    "error": ***
        "message": "ComputeTargetNotFound: Compute Target with name testml12 not found in provided workspace"
    ***
***

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/main.py", line 140, in <module>
    main()
  File "/code/main.py", line 128, in main
    compute_target = create_aks_cluster(
  File "/code/utils.py", line 86, in create_aks_cluster
    aks_config = AksCompute.provisioning_configuration(
  File "/usr/local/lib/python3.8/site-packages/azureml/core/compute/aks.py", line 255, in provisioning_configuration
    config = AksProvisioningConfiguration(agent_count, vm_size, ssl_cname, ssl_cert_pem_file, ssl_key_pem_file,
  File "/usr/local/lib/python3.8/site-packages/azureml/core/compute/aks.py", line 779, in __init__
    self.validate_configuration()
  File "/usr/local/lib/python3.8/site-packages/azureml/core/compute/aks.py", line 809, in validate_configuration
    raise ComputeTargetException('Invalid configuration, not all virtual net information provided. To use '
azureml.exceptions._azureml_exception.ComputeTargetException: ComputeTargetException:
	Message: Invalid configuration, not all virtual net information provided. To use a custom virtual net with aks, please provide vnet name, vnet resource group, subnet name, service cidr, dns service ip and docker bridge cidr
	InnerException None
	ErrorResponse 
***
    "error": ***
        "message": "Invalid configuration, not all virtual net information provided. To use a custom virtual net with aks, please provide vnet name, vnet resource group, subnet name, service cidr, dns service ip and docker bridge cidr"
    ***
***

**Comment by ma185360** [comment]
@marvinbuss Please help.

**Comment by marvinbuss** [comment]
Thanks @ma185360 for submitting this.
Is the AKS Cluster attached to the AML workspace?

Is the AKS Cluster listed in the compute Tab in AML?

**Comment by ma185360** [comment]
Thank you for the prompt response. Aks cluster is not attached to workspace or in compute Tab in AML. We assumed that giving the values in compute.json will create a new cluster and attached it to ML workspace like compute clusters.

**Comment by marvinbuss** [comment]
Sorry for the confusion. That is not the case yet.

Also, we have a compute action, which handles all compute related actions. Attaching AKS to AML is on the roadmap for https://github.com/Azure/aml-compute.

Can you please attach the AKS cluster manually to the AML workspace (ARM, CLI, REST, UI)? This is a one time process. Then, the aml-deploy should be able to handle all future deployments.

Would appreciate your feedback regarding the current setup. Would you like to see changes in the behavior of these Actions?

**Comment by ma185360** [comment]
okay. For now we'll attach it manually. Thanks again and those ML github actions are really helpful. Looking forward to the new features.

**Comment by marvinbuss** [comment]
Thanks for the feedback.

In the future, would you be ok with attaching the AKS with the aml-compute Action or do you want us to handle this automatically from aml-deploy?
We were thinking that users might not like us attaching the AKS automatically. Would appreciate your feedback!

**Comment by ma185360** [comment]
Yes, I think that would be great add-on. So we can deploy AKS separately using terraform and then ML-compute action can see if the mentioned cluster is attached or not. if not, then it will go-ahead and attach that cluster to the ML workspace.

**Comment by marvinbuss** [comment]
Thanks for the feedback. Will take this into account. Can you please let me know, whether they deployment works after attaching AKS to AML?

**Comment by marvinbuss** [comment]
Another comment on IaC: You can already attach an AKS to AML via ARM templates. Not sure whether that is already possible in Terraform. Since they are essentially another layer on top of ARM, it can take a while until Terraform catches up. This would be my preferred option rather than having the GH Action to execute some connection between AKS and AML.
But I will definitely take your comment into account. 👍

**Comment by marvinbuss** [comment]
Hi @ma185360 ,
Were you able to solve the issue?

**Comment by ma185360** [comment]
Srry, for the late response. Yes, issue got fixed with Public aks cluster. We are facing some issue while attaching private AKs to ML workspace but that has nothing to do with this one.

**Comment by marvinbuss** [comment]
Thanks @ma185360 ! I will take note of your feedback and add the request to our backlog. Also, I will close this issue.
